[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "beat-the-maths"
version = "0.1.0"
description = "A command-line math quiz game to test and improve your mathematic skills."
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [
    { name = "Vincent Mardon", email = "mardon.vincent@gmail.com"}
]
dependencies = [
    "pygame>=2.6.1,<3",
]

[project.optional-dependencies]
dev = [
    "build",
    "pytest",
    "ruff",
]

[project.scripts]
beat-the-maths = "beat_the_maths.__main__:main"
beat-the-maths-gui = "beat_the_maths.ui.pygame_app:main"

[tool.setuptools.packages.find]
include = ["beat_the_maths*"]

[tool.setuptools.package-data]
beat_the_maths = ["assets/*.ico"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
target-version = "py313"
line-length = 88

[tool.ruff.lint]
select = [
    "E4",
    "E7",
    "E9",
    "F",
    "I",
    "B",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

